# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wenhaohu/Dropbox/LLG_Code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wenhaohu/Dropbox/LLG_Code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wenhaohu/Dropbox/LLG_Code/CMakeFiles /Users/wenhaohu/Dropbox/LLG_Code/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wenhaohu/Dropbox/LLG_Code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Magnon

# Build rule for target.
Magnon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Magnon
.PHONY : Magnon

# fast build rule for target.
Magnon/fast:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/build
.PHONY : Magnon/fast

src/Basic.o: src/Basic.cpp.o

.PHONY : src/Basic.o

# target to build an object file
src/Basic.cpp.o:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/Basic.cpp.o
.PHONY : src/Basic.cpp.o

src/Basic.i: src/Basic.cpp.i

.PHONY : src/Basic.i

# target to preprocess a source file
src/Basic.cpp.i:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/Basic.cpp.i
.PHONY : src/Basic.cpp.i

src/Basic.s: src/Basic.cpp.s

.PHONY : src/Basic.s

# target to generate assembly for a file
src/Basic.cpp.s:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/Basic.cpp.s
.PHONY : src/Basic.cpp.s

src/DensityOfStates.o: src/DensityOfStates.cpp.o

.PHONY : src/DensityOfStates.o

# target to build an object file
src/DensityOfStates.cpp.o:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/DensityOfStates.cpp.o
.PHONY : src/DensityOfStates.cpp.o

src/DensityOfStates.i: src/DensityOfStates.cpp.i

.PHONY : src/DensityOfStates.i

# target to preprocess a source file
src/DensityOfStates.cpp.i:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/DensityOfStates.cpp.i
.PHONY : src/DensityOfStates.cpp.i

src/DensityOfStates.s: src/DensityOfStates.cpp.s

.PHONY : src/DensityOfStates.s

# target to generate assembly for a file
src/DensityOfStates.cpp.s:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/DensityOfStates.cpp.s
.PHONY : src/DensityOfStates.cpp.s

src/Faddeeva.o: src/Faddeeva.cpp.o

.PHONY : src/Faddeeva.o

# target to build an object file
src/Faddeeva.cpp.o:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/Faddeeva.cpp.o
.PHONY : src/Faddeeva.cpp.o

src/Faddeeva.i: src/Faddeeva.cpp.i

.PHONY : src/Faddeeva.i

# target to preprocess a source file
src/Faddeeva.cpp.i:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/Faddeeva.cpp.i
.PHONY : src/Faddeeva.cpp.i

src/Faddeeva.s: src/Faddeeva.cpp.s

.PHONY : src/Faddeeva.s

# target to generate assembly for a file
src/Faddeeva.cpp.s:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/Faddeeva.cpp.s
.PHONY : src/Faddeeva.cpp.s

src/FieldPlots.o: src/FieldPlots.cpp.o

.PHONY : src/FieldPlots.o

# target to build an object file
src/FieldPlots.cpp.o:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/FieldPlots.cpp.o
.PHONY : src/FieldPlots.cpp.o

src/FieldPlots.i: src/FieldPlots.cpp.i

.PHONY : src/FieldPlots.i

# target to preprocess a source file
src/FieldPlots.cpp.i:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/FieldPlots.cpp.i
.PHONY : src/FieldPlots.cpp.i

src/FieldPlots.s: src/FieldPlots.cpp.s

.PHONY : src/FieldPlots.s

# target to generate assembly for a file
src/FieldPlots.cpp.s:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/FieldPlots.cpp.s
.PHONY : src/FieldPlots.cpp.s

src/LLG.o: src/LLG.cpp.o

.PHONY : src/LLG.o

# target to build an object file
src/LLG.cpp.o:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/LLG.cpp.o
.PHONY : src/LLG.cpp.o

src/LLG.i: src/LLG.cpp.i

.PHONY : src/LLG.i

# target to preprocess a source file
src/LLG.cpp.i:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/LLG.cpp.i
.PHONY : src/LLG.cpp.i

src/LLG.s: src/LLG.cpp.s

.PHONY : src/LLG.s

# target to generate assembly for a file
src/LLG.cpp.s:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/LLG.cpp.s
.PHONY : src/LLG.cpp.s

src/Response.o: src/Response.cpp.o

.PHONY : src/Response.o

# target to build an object file
src/Response.cpp.o:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/Response.cpp.o
.PHONY : src/Response.cpp.o

src/Response.i: src/Response.cpp.i

.PHONY : src/Response.i

# target to preprocess a source file
src/Response.cpp.i:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/Response.cpp.i
.PHONY : src/Response.cpp.i

src/Response.s: src/Response.cpp.s

.PHONY : src/Response.s

# target to generate assembly for a file
src/Response.cpp.s:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/Response.cpp.s
.PHONY : src/Response.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Magnon.dir/build.make CMakeFiles/Magnon.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Magnon"
	@echo "... src/Basic.o"
	@echo "... src/Basic.i"
	@echo "... src/Basic.s"
	@echo "... src/DensityOfStates.o"
	@echo "... src/DensityOfStates.i"
	@echo "... src/DensityOfStates.s"
	@echo "... src/Faddeeva.o"
	@echo "... src/Faddeeva.i"
	@echo "... src/Faddeeva.s"
	@echo "... src/FieldPlots.o"
	@echo "... src/FieldPlots.i"
	@echo "... src/FieldPlots.s"
	@echo "... src/LLG.o"
	@echo "... src/LLG.i"
	@echo "... src/LLG.s"
	@echo "... src/Response.o"
	@echo "... src/Response.i"
	@echo "... src/Response.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

